branch-defaults:
  default:
    environment: MealPlanning-env
    group_suffix: null
  main:
    environment: MealPlanning-env
deploy:
  artifact: BackEnd/target/MealPlanning-0.0.1-SNAPSHOT.jar
global:
  application_name: MealPlanning
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 17 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
